export const CREATE_PLAN = 'CREATE_PLAN'; 
export const GET_PLANS = 'GET_PLANS'; 
export const GET_PLAN = 'GET_PLAN'; 
export const UPDATE_PLAN = 'UPDATE_PLAN'; 
export const DELETE_PLAN = 'DELETE_PLAN'; 

export const CREATE_LICENSE = 'CREATE_LICENSE'; 
export const GET_LICENSES = 'GET_LICENSES'; 
export const GET_LICENSE = 'GET_LICENSE'; 
export const UPDATE_LICENSE = 'UPDATE_LICENSE'; 
export const DELETE_LICENSE = 'DELETE_LICENSE'; 

export const CREATE_USER = 'CREATE_USER'; 
export const GET_USERS = 'GET_USERS'; 
export const GET_USER = 'GET_USER'; 
export const UPDATE_USER = 'UPDATE_USER'; 
export const DELETE_USER = 'DELETE_USER'; 

export const GET_ME = 'GET_ME'; 
export const UPDATE_ME = 'UPDATE_ME'; 
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD'; 
export const DELETE_ME = 'DELETE_ME'; 

export const GET_MONTHLY_REVENUE = 'GET_MONTHLY_REVENUE'; 
export const GET_SALES_STATS = 'GET_SALES_STATS'; 

export const CREATE_SUBSCRIPTION = 'CREATE_SUBSCRIPTION'; 
export const GET_SUBSCRIPTIONS = 'GET_SUBSCRIPTIONS'; 
export const GET_SUBSCRIPTION = 'GET_SUBSCRIPTION'; 
export const UPDATE_SUBSCRIPTION = 'UPDATE_SUBSCRIPTION'; 
export const DELETE_SUBSCRIPTION = 'DELETE_SUBSCRIPTION'; 

export const CREATE_TICKET = 'CREATE_TICKET'; 
export const GET_TICKETS = 'GET_TICKETS'; 
export const GET_TICKET = 'GET_TICKET'; 
export const UPDATE_TICKET = 'UPDATE_TICKET'; 
export const DELETE_TICKET = 'DELETE_TICKET'; 

export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION'; 
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS'; 
export const GET_NOTIFICATION = 'GET_NOTIFICATION'; 
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION'; 
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION'; 

export const CHECKOUT = 'CHECKOUT'; 